Dev1
nutanix-cloud-native/ndb-operator pull request #132
Opened 2023-07-20 23:32 UTC by mazin-s

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**How Has This Been Tested?**:

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and test output_

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

2023-07-24 16:54 UTC, shenoypritika commented
- Please modify the yaml in the READMe
- Please describe your tests in a line or two and attach a screenshot of
      - provisioned db in k8s using `kubectl get dbs`
      - provisioned db in the era UI
      - Response from the post call using the nodejs app (similar to the one you have attached)
- Please fix the title of the PR

2023-07-24 16:54 UTC, shenoypritika requested changes

2023-07-24 16:54 UTC, shenoypritika commented on config/samples/ndb_v1alpha1_database.yaml
Some changes here:

- Please revert your local changes to the db name and sla name. 
- Please add the description field in the databaseInstance spec with a sample value.

2023-07-24 16:54 UTC, shenoypritika commented on config/samples/ndb_v1alpha1_database.yaml
Also update the yaml in the READ.me with the new field

2023-07-24 20:43 UTC, mazin-s commented
> * Please modify the yaml in the READMe
> * Please describe your tests in a line or two and attach a screenshot of
>   - provisioned db in k8s using `kubectl get dbs`
>   - provisioned db in the era UI
>   - Response from the post call using the nodejs app (similar to the one you have attached)
> * Please fix the title of the PR

Resolved

2023-07-24 22:07 UTC, akshmish commented on api/v1alpha1/database_types.go
> +	Profiles *Profiles `json:"profiles"`
Why are these changes showing up in this PR? These don't seem to be related to this PR...

2023-07-24 22:07 UTC, akshmish commented on api/v1alpha1/database_webhook.go
> -		r.Spec.Instance.TimeZone = "UTC"
Same here, many of the Webhooks PR change are showing up here. Let's discuss it offline.

2023-07-25 18:22 UTC, manavrajvanshi approved these changes
Thanks for adding more unit tests.

2023-07-25 18:31 UTC, shenoypritika approved these changes

2023-07-25 18:31 UTC, akshmish commented on controller_adapters/database.go
> +		return "Database provisioned by ndb-operator: " + d.GetDBInstanceName()
Should we also add this in the database_webhook instance defaulter method?

2023-07-25 22:32 UTC, merged